import type { Metadata } from "next";
import NavigationBar from "@/components/kaming/header";
import Background from "@/components/kaming/background";
import Footer from "@/components/kaming/footer";
import { MockAuthProvider } from "@/lib/mockAuth";
import IntroAnimation from "@/components/IntroAnimation";
import "./globals.css";

export const metadata: Metadata = {
  title: "Trainity | Your Coding Tutor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MockAuthProvider>
          <IntroAnimation />
          <Background>
            <NavigationBar />
            {children}
            <Footer />
          </Background>
        </MockAuthProvider>
      </body>
    </html>
  );
}
